### ISSUE TITLE
Add correctness checks

### ISSUE THREAD

**Issue by IgorBaratta** [IgorBaratta/femtc#8]

**Comment by chrisrichardson** [comment]
This branch: https://github.com/IgorBaratta/femtc/tree/chris/verify has nanobind bindings to call the kernels from Python, but I didn't work out how exactly to check them, it is a bit more complicated trying to combine 1D basis functions together.

**Comment by IgorBaratta** [comment]
We can use the 3d basis function. We just need to make sure that we are using same quadrature rule.
